### ISSUE TITLE
Fetching origin error: pathspec '*' did not match any file(s) known to git

### ISSUE THREAD

**Issue by nimrossum** [platisd/bad-commit-message-blocker#6]
Hello, really cool project! 

I am experiencing an error when running this as a GitHub action:

```
Fetching origin
error: pathspec 'dotnet-refactor' did not match any file(s) known to git
```

This is my workflow file:

```yaml
name: Bad commit message blocker
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Bad commit message blocker
        uses: platisd/bad-commit-message-blocker@1.0.0
```

**Comment by platisd** [comment]
Hi!
Are you using it in a public project? Do you happen to have any link to the logs?

**Comment by platisd** [comment]
Also, are you passing the `github_token`? The minimum workflow should look something like this:

```yaml
name: Bad commit message blocker
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Bad commit message blocker
        uses: platisd/bad-commit-message-blocker@1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by nimrossum** [comment]
Strange, it used to work perfectly fine, without a token.

You can see the logging here:
https://github.com/themagicstrings/twooter/actions

**Comment by platisd** [comment]
Alright thanks for the link, it helped a lot and I believe I reproduced it. The following should fix it:

```yaml
name: Bad commit message blocker
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Bad commit message blocker
        uses: platisd/bad-commit-message-blocker@1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          remote_branch: "main"
```
Long story short, the problem is that there is no `master` branch, in your case it is called `main`.
The **very strange** thing is that `github_token` and `remote_branch` are supposed to be **required** attributes, so I am very surprised that they are not required for the Action to run in the first place.
In your case, while apparently `github_token` is not necessary (possibly because it's a public repository, this used to not be the case in the past), `remote_branch` is, since the default value used by the script is `master`.

Can you please try the fix out and let me know?
