### ISSUE TITLE
Github Action fails on git clone due to missing password

### ISSUE THREAD

**Issue by andersthorbeck** [platisd/bad-commit-message-blocker#7]
I have been trying to use this action with a private repository within an organization, but the action fails on the `git clone` step
```
eval git clone "https://${INPUT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" ${GITHUB_REPOSITORY}
```
within `entrypoint.sh` with error message

```
2021-09-15T13:20:41.3638436Z Cloning into 'myorganization/myrepository'...
2021-09-15T13:20:42.3342602Z fatal: could not read Password for 'https://***@github.com': No such device or address
```

The issue is that the `git clone` command requires a password when called with the github token as the HTTP username, and since no password is provided, the command fails.

My Github Actions workflow file `validate-chris-evans-commit-msg-guidelines.yaml`
```
name: Commit messages

on: [pull_request]

jobs:
  check-commit-message:
    runs-on: ubuntu-20.04
    steps:
      - name: Verify commit messages follow best practices in CI
        uses: platisd/bad-commit-message-blocker@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Optionally set the subject character limit (default `50`)
          subject_limit: 60
          # Optionally set the body character limit (default `72`)
          body_limit: 100
```
is pretty much a verbatim copy of the example workflow in the [`README.md`](https://github.com/platisd/bad-commit-message-blocker/blob/master/README.md#github-action) (except I'm leaving `remote_branch` with its default value, `master`).

The repository grants the `GITHUB_TOKEN` the permissive default access set of full read/write access to everything, as far as I can see
```
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
```
so lacking permissions should hardly be the problem.

I presume that this action works as intended with other repositories, so I don't see why the `git clone` command fails in my case. I have tried googling limitations of the `GITHUB_TOKEN` with `git clone`, but to no avail, finding instead only references to using Personal Access Tokens to achieving this. I have also tried reading the Github Actions documentation on the `GITHUB_TOKEN` to find why this would fail, but have found nothing relevant.

Attached are the complete logs from a run of a workflow job using this action, except with the organization and repository name replaced with `myorganization` and `myrepository` respectively.
[action-redacted.log](https://github.com/platisd/bad-commit-message-blocker/files/7176430/action-redacted.log)

Any idea what could be the issue here? Am I the only one experiencing this?
